//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticket_id { get; set; }
        public System.DateTime arrival_date { get; set; }
        public System.DateTime deperture_date { get; set; }
        public Nullable<int> number_of_customers { get; set; }
        public string vehicle_type { get; set; }
        public int vehicle_id { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
